### ISSUE TITLE
_.room.isStaff not working

### ISSUE THREAD

**Issue by Fuechschen** [anjanms/DubAPI#1]
For some reason, the function is not working for me, even if the bot-user is co-owner.

**Comment by anjanms** [comment]
Please give 0.2.0 a try. I've been busy and it took me a while to update.

Also please note, anything behind _ is API internals. For normal use nothing behind it should need to be accessed.

**Comment by Fuechschen** [comment]
works again. 
i'm ususally not using those methods but i tried to look for the reason of the problem directly in yout code.

**Comment by anjanms** [comment]
Okay, I didn't know. Thank you :)
