### ISSUE TITLE
User doesn't update correctly

### ISSUE THREAD

**Issue by Fuechschen** [anjanms/DubAPI#10]
It seems like usernames doesn't update if they are changed while the bot is in the room.

This could maybe come from listening to 'user-update' instead of listening to 'user_update_{userid}' like dubtrack-frontend does.

**Comment by anjanms** [comment]
You're correct, they do not update.

We are listening to ```user_update_{userid}```. But dubtrack doesn't emit an update when usernames change, nor does it seem to include usernames in any updates.

So, we're suffering from the same issue the frontend has. I've got an idea on how to resolve this, I'll work with it some this evening.

**Comment by anjanms** [comment]
Let me know if there's another event you feel should update usernames. But I think ```chat-message``` will cover it pretty well.
