### ISSUE TITLE
cannot call hasPermission of undefined

### ISSUE THREAD

**Issue by NitroGhost** [anjanms/DubAPI#12]
getting the following error when trying to delete a chat message:
![error](https://i.gyazo.com/6a1ec94c48cfdfa44903e63aa46b972e.png)
using 1.0.3

**Comment by anjanms** [comment]
Did the bot ban someone before this happened? Currently there is an issue with dubtrack where the server sends a user-leave event for the moderator instead of the user that was banned.

And this error is caused by the bot not being in the user array for the room anymore.

**Comment by NitroGhost** [comment]
no it hasn't. it sometimes seems to lose self from the user array. it's
happened 5 times now, 2 in a row where the bot crashed then auto restarted,
then crashed again when invoked

**Comment by anjanms** [comment]
Alright. All the stacktraces were similar to the one you provided? How much time was there between the bot connecting and it crashing when calling moderateDeleteChat?

**Comment by NitroGhost** [comment]
yeah they were the same stacktraces. and 2 mins or so

**Comment by anjanms** [comment]
Okay, I can't seem reproduce this. I can remove the bot from the array and get the same error, but I can't get it to happen on it's own. Do you notice anything common happen before each of these errors?

If not, can you add the following lines to listeners on the ```connected``` and ```user-leave``` events respectively? Change them to your logger if you've got one.

```javascript
console.log('[DEBUG]', 'Bot ID is: ' + bot._.self.id);
if (bot._.room.users.findWhere({id: bot._.self.id}, true) === undefined) {
    console.log('[DEBUG]', 'Bot not in room');
}
```

```javascript
//Where data is the object passed to the event
if (data.user.id === bot._.self.id) {
    console.log('[DEBUG]', 'Bot left the room');
}
```
Make sure the ID printed matches the account of your bot.

One of the other messages should print before that error occurs again. Let me know which one, and in the case of it leaving I'll need to know what happened just before.

**Comment by NitroGhost** [comment]
yeah I'll add those to my bot and see if they crop up at some point. the delete chat command doesn't get used often but I'll test periodically until it breaks

**Comment by NitroGhost** [comment]
alright finally got it. it's leaving the room apparently

**Comment by anjanms** [comment]
Alright. Did you notice anything aside from usual advancing/chatting/voting happen around the time the bot left?

Updating to 1.1.0 should resolve this symptom. The API will request to re-join the room when a leave event is received for the bot.
