### ISSUE TITLE
cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by NitroGhost** [anjanms/DubAPI#15]
welp, got bombarded with messages this morning about my bot connecting to dubtrack over and over. I have checked my logs and found this:

![cannot read property 'replace' of undefined](https://i.gyazo.com/85fc60c4453ef836d5d3634b304961fc.png)

**Comment by NitroGhost** [comment]
see brinkies issue

**Comment by qaisjp** [comment]
"Brinkies issue": #16
