### ISSUE TITLE
Support for uppercase in usernames

### ISSUE THREAD

**Issue by avatarkava** [anjanms/DubAPI#18]
Dubtrack apparently now supports uppercase letters in usernames - constructs like this will no longer work:
`var user = bot.getUserByName(input.toLowerCase());`

Removing toLowerCase() is a partial fix, but still requires the user to enter the case as an *exact* match.

Any thoughts on either:
* Adjusting bot.getUserByName() to do a case-insensitive search on the user list (probably needing a mixin for underscore) OR
* Storing all usernames in the user list in lowercase by default so that findWhere() works as expected

I think bot.getUserByName() is the only place this will apply in the DubAPI code, but you may be able to correct me if I'm wrong.

**Comment by NitroGhost** [comment]
are you sure uppercase doesn't work? ![test](http://i.imgur.com/oYEkc9E.png)

**Comment by NitroGhost** [comment]
nvm I se what you mean now :/
![test](http://i.imgur.com/1rgC0XZ.png)
