### ISSUE TITLE
queueMedia works, but does not join queue

### ISSUE THREAD

**Issue by mreinhardt** [anjanms/DubAPI#25]
Dubtrack recently added a "feature" where users are not automatically added to the room queue even if they have tracks in their room playlist. You either have to click the "Join Queue" button below the video or the "You are not in the room queue, click here to join :]" notification in the queue list.

The new `queueMedia` method does work! However, the bot doesn't join the queue due to the above. `joinQueue` and `leaveQueue` methods and functionality will need to be added.

**Comment by Fuechschen** [comment]
Try calling bot.pauseQueue(false)

**Comment by anjanms** [comment]
As @Fuechschen said; you 'join' and 'leave' the queue by calling `pauseQueue(false)` and `pauseQueue(true)` respectively.

There is a disconnect between what the front-end says and what it actually does.
The join/leave queue feature is actually the pause queue feature, just changed a bit.
