### ISSUE TITLE
queueMedia by YouTube or SoundCloud id

### ISSUE THREAD

**Issue by mreinhardt** [anjanms/DubAPI#26]
`queueMedia` works, but you need to use the Dubtrack song id which I haven't found a good way to look up easily. It's much easier to find YouTube or SoundCloud ids when using external track search APIs like EchoNest.

Would it be possible to add a feature where you can use `queueMedia` with the YouTube id (i.e. the `{id}` in `youtube.com/watch?v={id}`) or the SoundCloud song id?

**Comment by anjanms** [comment]
I'm not sure how you've got it working. The functionality you describe already exists.

`queueMedia` takes the media type and its ID. https://github.com/anjanms/DubAPI/wiki/methods#queuemedia

So for example if I wanted to queue https://www.youtube.com/watch?v=CKBV7vLirv8
I would do `queueMedia('youtube', 'CKBV7vLirv8');`
