### ISSUE TITLE
Where is module "ably"?

### ISSUE THREAD

**Issue by BrownHat** [anjanms/DubAPI#28]

**Comment by Fuechschen** [comment]
Run `npm install dubapi` and it will be installed automatically.

**Comment by BrownHat** [comment]
ok =_= http://prntscr.com/bnxje1

**Comment by Fuechschen** [comment]
This seem to be an issue with your computer. Install git and try again: https://github.com/npm/npm/wiki/Troubleshooting#no-git

**Comment by BrownHat** [comment]
It still error http://prntscr.com/bqnchv :| you should test a bot with dubapi . I will see.

**Comment by anjanms** [comment]
Looks like you don't have Python installed or it isn't in your `PATH`. [node-gyp](https://github.com/nodejs/node-gyp) requires Python 2.7.

**Comment by BrownHat** [comment]
when i tested it on tonicdev.com, It showed me this http://prntscr.com/c2wlm4
Cannot find module 'msgpack-js' ???

**Comment by Fuechschen** [comment]
You might should know dubbot !== dubapi. 

But this fails, since ably's msg-pack-version is not hosted on NPM, but on Github. You should install the package on your computer and see what happens.

**Comment by BrownHat** [comment]
I know it's a stupid question but how can i install it on my computer? @Fuechschen

**Comment by BrownHat** [comment]
"npm install dupapi"

**Comment by Fuechschen** [comment]
```npm install dubapi``` in the folder of your bot

**Comment by BrownHat** [comment]
I dont know but if it can work, Can you send me your "dubapi" folder :3 @Fuechschen

**Comment by Fuechschen** [comment]
Unfortunately i cannot since all my builds are on linux, so it won't work on a windows machine
