### ISSUE TITLE
Dubtrack Update broke some of their APIs

### ISSUE THREAD

**Issue by FranciscoG** [anjanms/DubAPI#32]
Looks like DT pushed an update that broke their API.  All bots are down.  

![from discord](http://i.imgur.com/vBM1wnL.png)

![and this](http://i.imgur.com/5hzN6sk.png)

**Comment by nine1six** [comment]
Thanks for the update. I was wondering what was going on. Also, what is the name of the Discord group? Is it public?

**Comment by FranciscoG** [comment]
here's the link:   [https://discord.gg/r7UEdpF](https://discord.gg/r7UEdpF)

you can find the link in DT's slide out menu:

![here](http://i.imgur.com/GO2Qr0w.png)

**Comment by nine1six** [comment]
Dope! Thanks.

**Comment by anjanms** [comment]
Please give 1.6.4 a try and let me know how it works.

**Comment by FranciscoG** [comment]
yay thanks for such a quick turnaround!  my bot's up again

**Comment by nine1six** [comment]
Working for me too. Thanks!
