### ISSUE TITLE
queuePlaylist error

### ISSUE THREAD

**Issue by FranciscoG** [anjanms/DubAPI#33]
I keep getting a 503 Service Unavailable when I try to use the [queuePlaylist](https://github.com/anjanms/DubAPI/blob/master/index.js#L224).

I get this:
```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Application Error</title>
<style media="screen">html,body,iframe{margin:0;padding:0;}html,body{height:100%;overflow:hidden;}iframe{width:100%;height:100%;border:0;}</style>
</head>
<body>
<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
</body>
</html>
```

**Comment by anjanms** [comment]
To me that looks like Heroku was throwing a fit at the time.  Can you still reproduce this?
It seems to be working for me now.

**Comment by FranciscoG** [comment]
still happening

Could it be because I'm queueing a rather large playlist?  I've got a playlist with 5,578 songs in it

**Comment by FranciscoG** [comment]
ok it's the playlist size.  I logged in as the bot user like normal and manually tried to queue the playlist and got the same response.   I bet my playlist size is what too large.  I'll have to trim it down and keep trying it until I find the acceptable amount.  So it's not a dubapi issue,  sorry to bug you!
