### ISSUE TITLE
rank/unrank

### ISSUE THREAD

**Issue by NitroGhost** [anjanms/DubAPI#9]
is it possible to add rank and unrank methods to the API? more bothered about the unranking more than anything. use case is if a VIP becomes toxic and you need to get them out the room, need to derank them before you're able to ban them

**Comment by Purnceks** [comment]
+1

**Comment by avatarkava** [comment]
Aren't those the moderateSetRole(uid, role, callback) and moderateUnsetRole(uid, role, callback) methods?

**Comment by NitroGhost** [comment]
wait, where are those, I don't see them on the wiki :open_mouth:

**Comment by avatarkava** [comment]
Wiki/docs are a bit out of date - check out https://github.com/anjanms/DubAPI/blob/master/index.js and look at the prototyped functions...

**Comment by NitroGhost** [comment]
ah alright cheers. TIL, don't trust wikis and check the source code instead
